// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP0UM-03U4g_N6b5XHegiV9oH8qBkLk3I',
    appId: '1:208926840684:web:4419e642586b8be780c549',
    messagingSenderId: '208926840684',
    projectId: 'base-app-f5a6e',
    authDomain: 'base-app-f5a6e.firebaseapp.com',
    storageBucket: 'base-app-f5a6e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjBKKq6r9MctUNZou3tlBAI6h3FIW8V3w',
    appId: '1:208926840684:android:2d6299af884424c280c549',
    messagingSenderId: '208926840684',
    projectId: 'base-app-f5a6e',
    storageBucket: 'base-app-f5a6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_qwgKQpQMgjZwZo9i7-uIIcfeaWsFDZ0',
    appId: '1:208926840684:ios:c2453930fa8a368f80c549',
    messagingSenderId: '208926840684',
    projectId: 'base-app-f5a6e',
    storageBucket: 'base-app-f5a6e.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseBoilerplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_qwgKQpQMgjZwZo9i7-uIIcfeaWsFDZ0',
    appId: '1:208926840684:ios:c2453930fa8a368f80c549',
    messagingSenderId: '208926840684',
    projectId: 'base-app-f5a6e',
    storageBucket: 'base-app-f5a6e.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseBoilerplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP0UM-03U4g_N6b5XHegiV9oH8qBkLk3I',
    appId: '1:208926840684:web:6269cdfb0837cdab80c549',
    messagingSenderId: '208926840684',
    projectId: 'base-app-f5a6e',
    authDomain: 'base-app-f5a6e.firebaseapp.com',
    storageBucket: 'base-app-f5a6e.firebasestorage.app',
  );
}
